In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("E:/Python Programs/DS/Datasets/shopping_trends.csv")

In [3]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Venmo,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Debit Card,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Debit Card,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Venmo,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,PayPal,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   str
 3   Item Purchased            3900 non-null   str
 4   Category                  3900 non-null   str
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   str
 7   Size                      3900 non-null   str
 8   Color                     3900 non-null   str
 9   Season                    3900 non-null   str
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   str
 12  Payment Method            3900 non-null   str
 13  Shipping Type             3900 non-null   str
 14  Discount Applied          3900 non-null   str
 15  Promo Code Used           3900 non-null   str
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   str
 18  Frequency of Purchases    3900 non-null   str
dtypes: float64(1), int64(4), str(14)
memory usage: 579.0 KB

In [6]:
df.describe(include='all') #include='all' gives us the details for all the columns and not just the numerical columns

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Credit Card,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,696,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [10]:
df.shape

(3900, 19)

In [14]:
#changing column names into snake case for better usability
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df= df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'payment_method',
       'shipping_type', 'discount_applied', 'promo_code_used',
       'previous_purchases', 'preferred_payment_method',
       'frequency_of_purchases'],
      dtype='str')

In [16]:
#creating a new column to group customers as per their age
labels= ['Young', 'Adult', 'Middle-Aged', 'Senior']
df['age_group']= pd.qcut(df['age'], 4 , labels=labels)

In [18]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-Aged
1   19        Young
2   50  Middle-Aged
3   21        Young
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27        Young
8   26        Young
9   57  Middle-Aged

In [21]:
df['frequency_of_purchases'].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [23]:
df['frequency_of_purchases'] = df['frequency_of_purchases'].replace({'Fortnightly' : 'Bi-Weekly', 'Every 3 Months' : 'Quarterly'})

In [24]:
df['frequency_of_purchases'].unique()

<StringArray>
['Bi-Weekly', 'Weekly', 'Annually', 'Quarterly', 'Monthly']
Length: 5, dtype: str

In [25]:
#creating a new column to judge purchase frequency days
frquency_mapping={
    'Weekly' : 7,
    'Annually' : 365,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Monthly' : 30
}

df['purchase_frequency_days']= df['frequency_of_purchases'].map(frquency_mapping)

In [29]:
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0              Bi-Weekly                       14
1              Bi-Weekly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [30]:
# checking the 2 columns 'discount_applied' and 'promo_code_used', the logic here is whenever a promo code will be used the discount will be there but a discount may be there in some cases where no promo code is used. so we will check if the columns are redundant and if we can remove any
df[['discount_applied', 'promo_code_used']].head(15)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes
11              Yes             Yes
12              Yes             Yes
13              Yes             Yes
14              Yes             Yes

In [37]:
#checking if the values in both the column same for all the rows
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [38]:
df= df.drop('promo_code_used', axis=1) # dropping the column 'promo_code_applied' as it is redundant in this case

In [39]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'payment_method',
       'shipping_type', 'discount_applied', 'previous_purchases',
       'preferred_payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [51]:
#Loading the dataset directly in MySQL
import urllib.parse
from sqlalchemy import create_engine
#Defining MySQL database credentials
user = "root"
password = "Anubhab@22"
safe_password = urllib.parse.quote_plus(password)
host= 'localhost'
port= '3306'
database_name = 'customer_behaviour_analysis_project'

#creating the connection engine
connection_string= ( f"mysql+pymysql://{user}:{safe_password}@{host}:{port}/{database_name}")
engine = create_engine(connection_string)

# Expoting the data frame ('df') to MYSQL
table_name= 'cust_data'
df.to_sql(
    table_name,
    con=engine,
    if_exists='replace',
    index= False,
)

print(f"Data exported successfully into table '{table_name}' in data base '{database_name}' to MySQL!")

Data exported successfully into table 'cust_data' in data base 'customer_behaviour_analysis_project' to MySQL!